<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VendorProductItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vendor_product_items')->delete();
        
        \DB::table('vendor_product_items')->insert(array (
            0 => 
            array (
                'id' => 89,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 408,
                'product_variant_id' => 17,
                'name' => 'Rice',
                'display_name' => 'Royal Stallion Golden Standard Rice - 5kg',
                'variant_label' => 'Royal Stallion Golden Standard Rice - 5kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774110860_0_j_QmNwqnb',
                'uom' => 'Kilogram',
                'weight' => '5.00',
                'quantity' => 0,
                'price' => '6478.92',
                'vendor_price' => '5999.00',
                'created_at' => '2026-04-02 05:28:02',
                'updated_at' => '2026-04-05 13:38:05',
            ),
            1 => 
            array (
                'id' => 90,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 408,
                'product_variant_id' => 18,
                'name' => 'Rice',
                'display_name' => 'Royal Stallion Golden Standard Rice - 10kg',
                'variant_label' => 'Royal Stallion Golden Standard Rice - 10kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774110863_1_XipfZlCyX',
                'uom' => 'Kilogram',
                'weight' => '10.00',
                'quantity' => 0,
                'price' => '10800.00',
                'vendor_price' => '10000.00',
                'created_at' => '2026-04-02 05:28:02',
                'updated_at' => '2026-04-05 16:28:36',
            ),
            2 => 
            array (
                'id' => 91,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 407,
                'product_variant_id' => 14,
                'name' => 'Rice',
                'display_name' => 'Cap Rice - 5kg',
                'variant_label' => 'Cap Rice - 5kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774110662_0_jUHooER2L',
                'uom' => 'Kilogram',
                'weight' => '5.00',
                'quantity' => 0,
                'price' => '8318.96',
                'vendor_price' => '7999.00',
                'created_at' => '2026-04-02 05:28:02',
                'updated_at' => '2026-04-12 20:35:06',
            ),
            3 => 
            array (
                'id' => 92,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 407,
                'product_variant_id' => 15,
                'name' => 'Rice',
                'display_name' => 'Cap Rice - 10kg',
                'variant_label' => 'Cap Rice - 10kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774110664_1_GMa1k5vND',
                'uom' => 'Kilogram',
                'weight' => '10.00',
                'quantity' => 0,
                'price' => '9360.00',
                'vendor_price' => '9000.00',
                'created_at' => '2026-04-02 05:28:02',
                'updated_at' => '2026-04-12 20:35:06',
            ),
            4 => 
            array (
                'id' => 93,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 406,
                'product_variant_id' => 12,
                'name' => 'Rice',
                'display_name' => 'Mama Gold Rice - 25kg',
                'variant_label' => 'Mama Gold Rice - 25kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774110505_2_pQQjvsnu2',
                'uom' => 'Kilogram',
                'weight' => '25.00',
                'quantity' => 1,
                'price' => '93600.00',
                'vendor_price' => '90000.00',
                'created_at' => '2026-04-02 05:28:02',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            5 => 
            array (
                'id' => 94,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 406,
                'product_variant_id' => 13,
                'name' => 'Rice',
                'display_name' => 'Mama Gold Rice - 50kg',
                'variant_label' => 'Mama Gold Rice - 50kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774110508_3_POd2gLsjY',
                'uom' => 'Kilogram',
                'weight' => '50.00',
                'quantity' => 0,
                'price' => '5198.96',
                'vendor_price' => '4999.00',
                'created_at' => '2026-04-02 05:28:02',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            6 => 
            array (
                'id' => 95,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 405,
                'product_variant_id' => 6,
                'name' => 'Rice',
                'display_name' => 'Big Bull Rice - 10kg',
                'variant_label' => 'Big Bull Rice - 10kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774109197_2_Nsf0ieyta',
                'uom' => 'Kilogram',
                'weight' => '10.00',
                'quantity' => 0,
                'price' => '8320.00',
                'vendor_price' => '8000.00',
                'created_at' => '2026-04-02 05:28:02',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            7 => 
            array (
                'id' => 96,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 405,
                'product_variant_id' => 8,
                'name' => 'Rice',
                'display_name' => 'Big Bull Rice - 50kg',
                'variant_label' => 'Big Bull Rice - 50kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774109201_4_kNWl44T75',
                'uom' => 'Kilogram',
                'weight' => '50.00',
                'quantity' => 0,
                'price' => '6238.96',
                'vendor_price' => '5999.00',
                'created_at' => '2026-04-02 05:28:02',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            8 => 
            array (
                'id' => 97,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 429,
                'product_variant_id' => 67,
            'name' => 'Rice - Foreign (Short grain, 1 Paint Bucket)',
            'display_name' => 'Rice - Foreign (Short grain, 1 Paint Bucket)',
            'variant_label' => 'Rice - Foreign (Short grain, 1 Paint Bucket)',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774716312_0_Lxlpgle6u',
                'uom' => 'Kilogram',
                'weight' => '3.50',
                'quantity' => 2,
                'price' => '6240.00',
                'vendor_price' => '6000.00',
                'created_at' => '2026-04-02 05:28:02',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            9 => 
            array (
                'id' => 98,
                'vendor_id' => 19,
                'category_id' => '32',
                'category_name' => 'Tubers & Roots',
                'product_id' => 414,
                'product_variant_id' => 41,
                'name' => 'Irish Potatoes',
                'display_name' => 'Irish Potatoes 1 kg',
                'variant_label' => 'Irish Potatoes 1 kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774710992_1_bmscanze7',
                'uom' => 'Kilogram',
                'weight' => '1.00',
                'quantity' => 0,
                'price' => '9360.00',
                'vendor_price' => '9000.00',
                'created_at' => '2026-04-18 16:19:20',
                'updated_at' => '2026-04-18 17:40:17',
            ),
            10 => 
            array (
                'id' => 99,
                'vendor_id' => 19,
                'category_id' => '32',
                'category_name' => 'Tubers & Roots',
                'product_id' => 414,
                'product_variant_id' => 42,
                'name' => 'Irish Potatoes',
                'display_name' => 'Irish Potato - Quarter Bag',
                'variant_label' => 'Irish Potato - Quarter Bag',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774710994_2_QNbcuVoSI',
                'uom' => 'Kilogram',
                'weight' => '12.50',
                'quantity' => 0,
                'price' => '20800.00',
                'vendor_price' => '20000.00',
                'created_at' => '2026-04-18 16:19:20',
                'updated_at' => '2026-04-18 17:40:18',
            ),
            11 => 
            array (
                'id' => 100,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 428,
                'product_variant_id' => 66,
            'name' => 'Rice - Foreign (Long grain, 1 Paint Bucket)',
            'display_name' => 'Rice - Foreign (Long grain, 1 Paint Bucket)',
            'variant_label' => 'Rice - Foreign (Long grain, 1 Paint Bucket)',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774716204_0_FixGhVd76',
                'uom' => 'Kilogram',
                'weight' => '3.50',
                'quantity' => 99,
                'price' => '4160.00',
                'vendor_price' => '4000.00',
                'created_at' => '2026-04-18 17:47:01',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            12 => 
            array (
                'id' => 101,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 427,
                'product_variant_id' => 65,
            'name' => 'Ofada Rice (Paint Bucket)',
            'display_name' => 'Ofada Rice (Paint Bucket)',
            'variant_label' => 'Ofada Rice (Paint Bucket)',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774716067_0_zPafynUn0',
                'uom' => 'Kilogram',
                'weight' => '3.50',
                'quantity' => 99,
                'price' => '5200.00',
                'vendor_price' => '5000.00',
                'created_at' => '2026-04-18 17:47:01',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            13 => 
            array (
                'id' => 102,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 410,
                'product_variant_id' => 26,
                'name' => 'Oats',
                'display_name' => 'Quaker Oats - 500g Refill',
                'variant_label' => 'Quaker Oats - 500g Refill',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774706976_0_R0pK1WK0K',
                'uom' => 'Gram',
                'weight' => '500.00',
                'quantity' => 14,
                'price' => '5824.00',
                'vendor_price' => '5600.00',
                'created_at' => '2026-04-18 17:47:01',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            14 => 
            array (
                'id' => 103,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 408,
                'product_variant_id' => 25,
                'name' => 'Rice',
                'display_name' => 'Royal Stallion Golden Standard Rice - 50kg',
                'variant_label' => 'Royal Stallion Golden Standard Rice - 50kg',
                'logo' => 'http://127.0.0.1:8001/images/products/variant_1774706124_3_1774706124_69c7ddcc196ed.webp',
                'uom' => 'Kilogram',
                'weight' => '50.00',
                'quantity' => 11,
                'price' => '4680.00',
                'vendor_price' => '4500.00',
                'created_at' => '2026-04-18 17:47:01',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            15 => 
            array (
                'id' => 104,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 426,
                'product_variant_id' => 64,
            'name' => 'Rice - Local (Paint Bucket)',
            'display_name' => 'Rice - Local (Paint Bucket)',
            'variant_label' => 'Rice - Local (Paint Bucket)',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774715950_0_OGvhMDVmk',
                'uom' => 'Kilogram',
                'weight' => '3.50',
                'quantity' => 4,
                'price' => '2078.96',
                'vendor_price' => '1999.00',
                'created_at' => '2026-04-25 17:18:34',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            16 => 
            array (
                'id' => 105,
                'vendor_id' => 19,
                'category_id' => '31',
                'category_name' => 'Grains & Cereals',
                'product_id' => 409,
                'product_variant_id' => 21,
                'name' => 'Ofada Rice',
                'display_name' => 'Ofada Rice 2kg',
                'variant_label' => 'Ofada Rice 2kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774112556_1_caE1T0Blv',
                'uom' => 'Kilogram',
                'weight' => '2.00',
                'quantity' => 4,
                'price' => '3118.96',
                'vendor_price' => '2999.00',
                'created_at' => '2026-04-25 17:18:34',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            17 => 
            array (
                'id' => 106,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 425,
                'product_variant_id' => 60,
                'name' => 'White Beans',
                'display_name' => 'White Beans Full Bag',
                'variant_label' => 'White Beans Full Bag',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774715812_0_uVM4BHEBV',
                'uom' => 'Kilogram',
                'weight' => '100.00',
                'quantity' => 9,
                'price' => '1248.00',
                'vendor_price' => '1200.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            18 => 
            array (
                'id' => 107,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 425,
                'product_variant_id' => 61,
                'name' => 'White Beans',
                'display_name' => 'White Beans Half Bag',
                'variant_label' => 'White Beans Half Bag',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774715815_1_Gc7IemEsk',
                'uom' => 'Kilogram',
                'weight' => '50.00',
                'quantity' => 99,
                'price' => '5200.00',
                'vendor_price' => '5000.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            19 => 
            array (
                'id' => 108,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 425,
                'product_variant_id' => 63,
                'name' => 'White Beans',
                'display_name' => 'White Beans 1/8 Bag',
                'variant_label' => 'White Beans 1/8 Bag',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774715823_3_fcqqWu4ZR',
                'uom' => 'Kilogram',
                'weight' => '12.50',
                'quantity' => 148,
                'price' => '5720.00',
                'vendor_price' => '5500.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            20 => 
            array (
                'id' => 109,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 424,
                'product_variant_id' => 56,
                'name' => 'Oloyin Beans',
                'display_name' => 'Oloyin Beans Full Bag',
                'variant_label' => 'Oloyin Beans Full Bag',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774715425_0_qAvBWsfmG',
                'uom' => 'Kilogram',
                'weight' => '100.00',
                'quantity' => 10,
                'price' => '4680.00',
                'vendor_price' => '4500.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:30:52',
            ),
            21 => 
            array (
                'id' => 110,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 424,
                'product_variant_id' => 57,
                'name' => 'Oloyin Beans',
                'display_name' => 'Oloyin Beans Half Bag',
                'variant_label' => 'Oloyin Beans Half Bag',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774715428_1_hDn9xdnpO',
                'uom' => 'Kilogram',
                'weight' => '50.00',
                'quantity' => 15,
                'price' => '3536.00',
                'vendor_price' => '3400.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:30:52',
            ),
            22 => 
            array (
                'id' => 111,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 424,
                'product_variant_id' => 58,
                'name' => 'Oloyin Beans',
                'display_name' => 'Oloyin Beans Quarter Bag',
                'variant_label' => 'Oloyin Beans Quarter Bag',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774715431_2_85hr-6Btt',
                'uom' => 'Kilogram',
                'weight' => '25.00',
                'quantity' => 155,
                'price' => '5824.00',
                'vendor_price' => '5600.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:43:31',
            ),
            23 => 
            array (
                'id' => 112,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 422,
                'product_variant_id' => 53,
                'name' => 'Brown Beans',
                'display_name' => 'Ayoola Foods Brown Beans 1.8 kg',
                'variant_label' => 'Ayoola Foods Brown Beans 1.8 kg',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774714983_0_pCm5PFvOG',
                'uom' => 'Kilogram',
                'weight' => '1.80',
                'quantity' => 100,
                'price' => '4160.00',
                'vendor_price' => '4000.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:30:52',
            ),
            24 => 
            array (
                'id' => 113,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 422,
                'product_variant_id' => 54,
                'name' => 'Brown Beans',
                'display_name' => 'Ayoola Foods Brown Beans 900 g',
                'variant_label' => 'Ayoola Foods Brown Beans 900 g',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774714986_1_hVtnGl--3',
                'uom' => 'Kilogram',
                'weight' => '0.90',
                'quantity' => 134,
                'price' => '2392.00',
                'vendor_price' => '2300.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:30:52',
            ),
            25 => 
            array (
                'id' => 114,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 421,
                'product_variant_id' => 52,
                'name' => 'Lentils',
                'display_name' => 'East End Brown Lentils 500 g',
                'variant_label' => 'East End Brown Lentils 500 g',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774714630_0_W93L6rql2',
                'uom' => 'Kilogram',
                'weight' => '0.50',
                'quantity' => 100,
                'price' => '3536.00',
                'vendor_price' => '3400.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:30:52',
            ),
            26 => 
            array (
                'id' => 115,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 418,
                'product_variant_id' => 50,
            'name' => 'Beans - Oloyin (Paint Bucket)',
            'display_name' => 'Beans - Oloyin (Paint Bucket)',
            'variant_label' => 'Beans - Oloyin (Paint Bucket)',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774713770_0_jy8K_4sh-',
                'uom' => 'Kilogram',
                'weight' => '3.50',
                'quantity' => 49,
                'price' => '6968.00',
                'vendor_price' => '6700.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:30:52',
            ),
            27 => 
            array (
                'id' => 116,
                'vendor_id' => 20,
                'category_id' => '33',
                'category_name' => 'Beans & Legumes',
                'product_id' => 419,
                'product_variant_id' => 51,
            'name' => 'Beans - White (Paint Bucket)',
            'display_name' => 'Beans - White (Paint Bucket)',
            'variant_label' => 'Beans - White (Paint Bucket)',
                'logo' => 'https://ik.imagekit.io/hjhce3bcsi/products/variant_1774713977_0_yztrcUGtE',
                'uom' => 'Kilogram',
                'weight' => '3.50',
                'quantity' => 100,
                'price' => '4680.00',
                'vendor_price' => '4500.00',
                'created_at' => '2026-04-28 09:30:52',
                'updated_at' => '2026-04-28 09:43:31',
            ),
        ));
        
        
    }
}